services:
  - type: web
    name: pg-rental-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://pg-rental-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html